module.exports = {
  type: 'mysql',
  host: process.env.DB_HOST || 'localhost',
  port: process.env.DB_PORT ? parseInt(process.env.DB_PORT, 10) : 3306,
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  entities: ['src/entity/*.entity{.ts,.js}'],
  migrations: ['src/database/migration/*{.ts,.js}'],
  seeds: ['src/database/seed/*{.ts,.js}'],
  cli: {
    migrationsDir: 'src/database/migration',
    entitiesDir: 'src/entity',
  },
  timezone: 'Z',
  dateStrings: true,
  charset: 'utf8mb4',
  synchronize: false,
  logging: process.env.NODE_ENV === 'dev' ? ['query', 'error'] : false,
};
